branches:
  only:
    - develop
    - "11"
language: node_js
node_js:
  - "4.4"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN